x-humanoid-tianyi2:
  image: __IMAGE__
  container_name: embodied-x-humanoid-tianyi2
  privileged: true
  volumes:
    - /dev:/dev
  environment:
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - PYTHONUNBUFFERED=1
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
